### PR TITLE
Clean deployment files

### PR DESCRIPTION
**Pull request by sebastian-aranda**
This PR clean and refactor some deployment codes. There were some legacy deployments that needed to be changed and some static routings that also needed to be changed

### CODE REVIEW

**Review by mareuter — COMMENTED** [review]
I see that the manager static directory is going away. Will this be with a new release of the manager? Also, it looks like the `nginx.conf` files for `ncsa` and `tucson` did not get updated like the ones for `summit` and `summit2` did. Any reason for the difference?

**Comment by sebastian-aranda** [comment]
> I see that the manager static directory is going away. Will this be with a new release of the manager? Also, it looks like the `nginx.conf` files for `ncsa` and `tucson` did not get updated like the ones for `summit` and `summit2` did. Any reason for the difference?
Really it doesn't go away, the manager (django) already handles the routing to the static files. Setting the volume and a route on nginx was unnecessary, thus we removed those directives.

I've updated the missing files of `ncsa` and `tucson`. Thanks for the reminder.

I've also added an extra route regarding the `media` folder. Different to the `static` folder, that is handled by django, the `media` folder is custom to the project, thus we need the routes on the `nginx.conf` files. I set two routes: `/media` and `/media/manager`. This is needed because we have some parts of the codes which references to the `/media` folder and other were it calls the `/media/manager`. We should refactor this in the future, but for the moment we found this solution.

**Review by mareuter — APPROVED** [review]
Thank you for the explanation and the fixes. This looks good to me.

**Review by areyesd14 — APPROVED** [review]
Looks good for me. Thanks @sebastian-aranda !

**Pull request merged**
