### PR TITLE
tickets/DM-28221

### PR DESCRIPTION
**Pull request by mareuter**

### CODE REVIEW

**Review by sebastian-aranda — APPROVED** [review]

**Review by tribeiro — COMMENTED** [review]
Is this PR still relevant? do you want to supersede it with something more recent?

**Review by tribeiro — CHANGES_REQUESTED** [review]
Is this PR still relevant? do you want to supersede it with something more recent?

**Comment by mareuter** [comment]
I'm still sitting on the fence about the producer version. However, this change is only localized to the cycle number so I don't see a real problem with merging it.

**Review by tribeiro — APPROVED** [review]
Changes looks good to me... but please, before merging, rebase to the current develop branch...

**Pull request merged**
