### PR TITLE
tickets/DM-31069

### PR DESCRIPTION
**Pull request by mareuter**

### CODE REVIEW

**Review by sebastian-aranda — APPROVED** [review]
Everything looks good. I wonder if `LOVE_SITE=summit` should be added to `deploy/summit/.env` and `deploy/summit2/.env` too. Also the `LOVE_CSC_PRODUCER` variable should be deprecated once we have the new version the LOVE-producer. It is currently only used to set they system in the legacy mode (the first version which used only 3 producers for events, telemetries and heartbeat on all CSCs at one time) if it is false, if the variable is not set the LOVE-manager assumes the default value as True

**Review by tribeiro — APPROVED** [review]

**Comment by sebastian-aranda** [comment]
@mareuter and @tribeiro , do you really use the `local/build/` files for your deployment?

**Comment by mareuter** [comment]
I only used it for local development when working on the view stuff. We use the site specific directories for deployment.

**Comment by sebastian-aranda** [comment]
> I only used it for local development when working on the view stuff. We use the site specific directories for deployment.

I would like to make some updates to the `local/build/docker-compose.yml` on a next PR. I will ask for your feedback @mareuter to check if the changes doesn't affect your pipeline

**Pull request merged**
